### PR TITLE
fix gamma_inc max precision case

### LINKED ISSUE #204: Incomplete gamma error
I have a problem with incomplete gamma calculation in Julia 1.1
```
gamma_inc(10^7, 10^7+1, 0)
```
gives error
```
ERROR: UndefVarError: u not defined
Stacktrace:
 [1] gamma_inc_minimax(::Float64, ::Float64, ::Float64) at /Users/User/.julia/packages/SpecialFunctions/ne2iw/src/gamma_inc.jl:550
 [2] gamma_inc(::Float64, ::Float64, ::Int64) at /Users/User/.julia/packages/SpecialFunctions/ne2iw/src/gamma_inc.jl:852
 [3] gamma_inc(::Int64, ::Int64, ::Int64) at /Users/User/.julia/packages/SpecialFunctions/ne2iw/src/gamma_inc.jl:910
 [4] top-level scope at none:0
```
Also gamma_inc(10^7, 1+10^7, 2) works ok, but 
```
gamma_inc(10^7, 1+10^7, 3)
```
gives 
```
ERROR: BoundsError: attempt to access 3-element Array{Float64,1} at index [4]
Stacktrace:
 [1] getindex at ./array.jl:729 [inlined]
 [2] gamma_inc(::Float64, ::Float64, ::Int64) at /Users/User/.julia/packages/SpecialFunctions/ne2iw/src/gamma_inc.jl:806
 [3] gamma_inc(::Int64, ::Int64, ::Int64) at /Users/User/.julia/packages/SpecialFunctions/ne2iw/src/gamma_inc.jl:910
 [4] top-level scope at none:0
```
Similar problem with inverse function, for example
```
gamma_inc_inv(10^7, 3/4, 1/4)
```
gives 
```
ERROR: UndefVarError: u not defined
Stacktrace:
 [1] gamma_inc_minimax(::Float64, ::Float64, ::Float64) at /Users/User/.julia/packages/SpecialFunctions/ne2iw/src/gamma_inc.jl:550
 [2] gamma_inc(::Float64, ::Float64, ::Int64) at /Users/User/.julia/packages/SpecialFunctions/ne2iw/src/gamma_inc.jl:852
 [3] gamma_inc_inv(::Float64, ::Float64, ::Float64) at /Users/User/.julia/packages/SpecialFunctions/ne2iw/src/gamma_inc.jl:973
 [4] gamma_inc_inv(::Int64, ::Float64, ::Float64) at /Users/User/.julia/packages/SpecialFunctions/ne2iw/src/gamma_inc.jl:998
 [5] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by birm**
It looks like the wrong variable was used in the source; this should fix it!

closes #204

### CODE REVIEW

**Comment by simonbyrne** [comment]
Thanks! Any chance you could add a test to exercise this branch?

**Comment by simonbyrne** [comment]
Hmm, the diff is messed up, you might need to rebase.

**Comment by birm** [comment]
_there_ we go.

**Comment by simonbyrne** [comment]
Thanks!

**Pull request merged**
