### PR TITLE
Use OS and arch only instead of triplets

### PR DESCRIPTION
**Pull request by ararslan**
@colbec, @H-M-H, @TomCab: Can you try
```julia
Pkg.checkout("SpecialFunctions")
Pkg.checkout("SpecialFunctions", "aa/no-triplets")
Pkg.build("SpecialFunctions")
using SpecialFunctions
```
and tell me whether it works for you?

### CODE REVIEW

**Comment by colbec** [comment]
Works for me on openSUSE Leap 42.3. Also Pkg.test("SpecialFunctions") works.

**Comment by ararslan** [comment]
Fantastic, thanks for checking. I'll get this tagged ASAP, then you can `Pkg.free("SpecialFunctions")` and `Pkg.update()` to get the latest tagged version.

**Comment by H-M-H** [comment]
Can confirm, building master works now.

**Comment by ararslan** [comment]
Awesome. Just waiting on https://github.com/JuliaLang/METADATA.jl/pull/11144, then you can upgrade to 0.3.3.

**Comment by tkelman** [comment]
This isn't right, the linux download should not be used on non-glibc distributions.

**Comment by tkelman** [comment]
Instead this should be whitelisting x86_64-redhat-linux and other equivalent triples that are known to work, not using glibc-specific binaries on all x86_64 linux triples. There's also clearly something broken about the source build fallback.

**Comment by ararslan** [comment]
Which non-glibc Linux distros does Julia work on? I didn't think LLVM was compatible with musl. If this turns out to be a problem with some distro I can change it but it's not a high priority for me until someone comes across an issue with the binaries.

Regarding the source build fallback, I'm unable to reproduce the issues people have been seeing.

**Comment by tkelman** [comment]
There's a build for alpine linux. LLVM just needs patches that distros have but haven't been upstreamed.

The issue this is fixing is "a problem with some distro" - you've traded wrong in some cases for wrong in a more broken way elsewhere. You shouldn't be using binaries when they won't work.

**Comment by ararslan** [comment]
If you have a better approach in mind, please submit a PR with that change.

**Comment by tkelman** [comment]
Revert this. Add additional whitelisted triples that map to the same binaries.

**Comment by ararslan** [comment]
Again, if you think the whitelist approach is the way to go here, please submit that as a PR.

**Pull request merged**
