### PR TITLE
Use binaries from Yggdrasil

### LINKED ISSUE #179: Pull binaries from Yggdrasil now that openspecfun is in
The [openspecfun builder](https://github.com/JuliaPackaging/Yggdrasil/pull/34) is now available in Yggdrasil and we have [openspecfun binaries](https://github.com/JuliaPackaging/Yggdrasil/releases/tag/OpenSpecFun-v0.5.3%2B0)

How do we generate the `build_info` and move the downloads over?

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #179.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Do we need to tag and release next?

**Comment by ViralBShah** [comment]
I am not sure I did this right: https://github.com/JuliaRegistries/General/pull/3142

Does TagBot tag the release after Registrator PR is merged?

**Comment by giordano** [comment]
> Does TagBot tag the release after Registrator PR is merged?

Yes

**Comment by ViralBShah** [comment]
Thanks. It all works.

**Pull request merged**
