### PR TITLE
Copied tests and some definitions from base

### PR DESCRIPTION
**Pull request by ararslan**
Let's see what happens to the coverage and CI...

### CODE REVIEW

**Comment by ararslan** [comment]
...the answer appears to be "not good things."

In this repo we're doing some of the bessel return values with `oftype(x, ...)`, which is omitted in Base. Should we just copy what Base is doing or is there a good reason to be doing it this way? cc @tkelman

**Comment by tkelman** [comment]
I'm not sure! What is the type difference if you leave out the `oftype`? Can you see anything in the history of the base files where maybe it was changed at some point that this repo missed?

**Comment by ararslan** [comment]
I can check the return type differences a little later but in the meantime I was able to find the commit that removed the `oftype`s: https://github.com/JuliaLang/julia/commit/8077d116e22f12342bc392c54eedc470d9d5f2ef

@simonbyrne As the one who introduced the change, can you provide some insight into this?

**Comment by simonbyrne** [comment]
As the commit comment mentions, it was to fix https://github.com/JuliaLang/julia/issues/11512

**Comment by ararslan** [comment]
Right, that fixed the reported issue with `BigFloat`s, I was just wondering if there was any other justification for that particular solution since removing `oftype` seems like it would make the return type less predictable.

**Comment by ararslan** [comment]
In particular, it looks like one of the test failures was because `oftype` was converting the return type, which would otherwise have been a float, to complex to match the argument's type. No idea whether that's desirable.

**Comment by ararslan** [comment]
First of all, sorry for the month and a half delay in getting this done.

I think I had misinterpreted the errors before; I don't think Simon's removal of `oftype` was actually causing the type difference I was seeing. It appears it was a thing with the 0.4 version of `isapprox` that Simon has since fixed in base. Sorry for the confusion, and thanks to Simon for fixing `isapprox`!

I worked around the `isapprox` difference in here and got all AMOS-based code and tests copied over from base.

**Pull request merged**
