### PR TITLE
Add ChainRules definitions for `gamma(a, x)`, `loggamma(a, x)`, and `gamma_inc`

### PR DESCRIPTION
**Pull request by devmotion**
I added ChainRules definitions for `gamma(a, x)`, `loggamma(a, x)`, and `gamma_inc` according to https://functions.wolfram.com/GammaBetaErf/GammaRegularized/introductions/Gammas/ShowAll.html. Similar to the Bessel functions, derivatives with respect to the first argument `a` are not implemented since they are given in terms of a (regularized) hypergeometric function.

Unfortunately, it seems due to the error thrown for derivatives of the first argument these rules can't be tested with `test_frule` and `test_rrule` since these functions always unthunk all derivatives. It would be good if one could somehow exclude some derivatives from the tests completely and not only from the finite differencing checks. I'll open an issue in ChainRulesTestUtils regarding this question.

(BTW I assume that due to this issue the derivatives of the Bessel functions are not tested currently)

### CODE REVIEW

**Comment by stevengj** [comment]
Great, thanks!  It would be good to resolve the testing question.

**Comment by devmotion** [comment]
Soon it will be possible to test (existing and new) partially implemented differentials properly: https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/140

**Comment by andreasnoack** [comment]
Should this one be update now that https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/140 is merged?

**Comment by andreasnoack** [comment]
The drone runs seems to have connectivity issues. Not sure why.

**Pull request merged**
