### PR TITLE
simplify Amos exception

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by musm** [comment]
True, we can at least get rid of some of the errors in favor of Julia equivalents.

**Comment by simonbyrne** [comment]
Actually, I'm not sure there are sufficient ones. e.g. `OverflowError` is mainly used for integer overflow (the floating point equivalent would be to return Inf (or possibly NaN if part of an intermediate computation)

**Comment by musm** [comment]
What about `ArgumentError`  for e.g. id == 1 ?

**Comment by simonbyrne** [comment]
That seems reasonable.

**Pull request merged**
