### PR TITLE
Replace `DoesNotExist` with `NoTangent`

### PR DESCRIPTION
**Pull request by devmotion**
Tests pass successfully locally with this PR.

### CODE REVIEW

**Comment by devmotion** [comment]
@oxinabox should one update the lower bounds of ChainRulesCore and/or ChainRulesTestUtils? I lost a bit track of when the different deprecations were introduced and removed.

**Comment by oxinabox** [comment]
Oops I missed this in #319 

It seems this function doesn't have tests, or they would have failed.
I guess becaues we didn't have support for NotImplemented in ChainRulesTestUtils yet?
We should add those tests?


>  should one update the lower bounds of ChainRulesCore and/or ChainRulesTestUtils?

No, I updated them in #319.
At least the ones for ChainRulesCore are correct for this.

**Comment by devmotion** [comment]
> Why didn't CI fail there?

Because tests used ChainRulesCore 0.9.45 which only deprecates `DoesNotExist`: e.g., https://github.com/JuliaMath/SpecialFunctions.jl/runs/2718082508#step:6:97

**Comment by devmotion** [comment]
Tests on master and in other PRs use ChainRulesCore 0.10 in which `DoesNotExist` is not defined anymore.

**Comment by giordano** [comment]
I take this is good to go?  I'm going to merge as soon as CI finishes

**Comment by devmotion** [comment]
Can you also make a new release?

**Comment by oxinabox** [comment]
> Tests on master and in other PRs use ChainRulesCore 0.10 in which DoesNotExist is not defined anymore.

Bother. I thought I checked that it actually updated.
I wonder why it didn't.
Given nothing has changed in Compat for this PR and now it is updating.

**Pull request merged**
