### PR TITLE
add multivariate gamma function (multgam)

### PR DESCRIPTION
**Pull request by Jan-van-Waaij**
Add multivariate gamma function: https://en.wikipedia.org/wiki/Multivariate_gamma_function

### CODE REVIEW

**Comment by simonbyrne** [comment]
Is this really the most efficient way to compute this? It would seem that you should be able to leverage the recurrence relation of the gamma function to reduce the evaluation of `gamma` to 2 points. Also, I imagine that a log-transformed variant would be useful to avoid overflow.

**Comment by simonbyrne** [comment]
You might be able to make use of the duplication formula (https://dlmf.nist.gov/5.5.5) as well.

**Comment by Jan-van-Waaij** [comment]
You are right! I going to figure it out.

**Comment by Jan-van-Waaij** [comment]
I don't think it is possible to reduce the multivariate gamma function to evaluation of gamma at at most 2 points, as n=2 in formula [https://dlmf.nist.gov/5.5#E6](https://dlmf.nist.gov/5.5#E6). Thus we can reduce the number of gamma evaluations to at most ceil(n/2).

**Comment by Jan-van-Waaij** [comment]
The log multivariate gamma function is defined in the package StatsFuns.jl as logmvgamma.

**Pull request closed without merging**
