### PR TITLE
docs for erf(x,y)

### PR DESCRIPTION
**Pull request by cossio**
Add docs for https://github.com/JuliaMath/SpecialFunctions.jl/pull/223

### CODE REVIEW

**Comment by cossio** [comment]
The CI failure doesn't look related to the PR. Some unrelated AWS issue.

**Comment by cossio** [comment]
Hmm, why I don't see the docs here: https://juliamath.github.io/SpecialFunctions.jl/dev/functions_list/

**Comment by ararslan** [comment]
I'm not sure. I have a hunch that I'm checking in #225 but we'll see whether that makes a difference.

**Comment by cossio** [comment]
Ah, I see the doc changes now.

**Pull request merged**
