### PR TITLE
Use our own Travis badge

### PR DESCRIPTION
**Pull request by ararslan**
The badge in the README is currently using nolta's Travis status.

### CODE REVIEW

**Comment by ararslan** [comment]
Uhhhh I don't know what I did but for some reason the commits from both of my open PRs are listed here... This one is on a separate branch so I don't understand why that happened.

**Comment by tkelman** [comment]
> Edit: Maybe because my other PR is coming from my master branch?

Likely. Best to avoid that, make a new branch per PR.

**Comment by ararslan** [comment]
Yeah, the fact that it was from my master was an oversight on my part.

**Comment by ararslan** [comment]
I can merge this PR and close the other one since this is on a new branch and incorporates both changes, if that seems reasonable. I also have another branch that I'll open a PR for soon that aims at getting Travis to cooperate...

**Pull request merged**
