### PR TITLE
Updates for new BinaryBuilder, simplifications for 0.7

### LINKED ISSUE #117: error building SpecialFunctions on 1.0, Linux
See the error below when trying to build `SpecialFunctions`:
```
(v1.0) pkg> add SpecialFunctions
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
  [276daf66] + SpecialFunctions v0.7.0
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]

(v1.0) pkg> build SpecialFunctions
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/KvXoO/deps/build.log`
┌ Error: Error building `SpecialFunctions`: 
│ ┌ Warning: Could not extract the platform key of https://github.com/JuliaMath/OpenspecfunBuilder/releases/download/v0.5.3-1/libopenspecfun.x86_64-linux-gnu.tar.gz; continuing...
│ └ @ BinaryProvider ~/.julia/packages/BinaryProvider/UTYxu/src/Prefix.jl:224
│ [ Info: Downloading https://github.com/JuliaMath/OpenspecfunBuilder/releases/download/v0.5.3-1/libopenspecfun.x86_64-linux-gnu.tar.gz to /home/mlubin/.julia/packages/SpecialFunctions/KvXoO/deps/usr/downloads/libopenspecfun.x86_64-linux-gnu.tar.gz...
│ ERROR: LoadError: Could not download https://github.com/JuliaMath/OpenspecfunBuilder/releases/download/v0.5.3-1/libopenspecfun.x86_64-linux-gnu.tar.gz to /home/mlubin/.julia/packages/SpecialFunctions/KvXoO/deps/usr/downloads/libopenspecfun.x86_64-linux-gnu.tar.gz:
│ ErrorException("")
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] macro expansion at ./logging.jl:313 [inlined]
│  [3] #download#89(::Bool, ::Function, ::String, ::String) at /home/mlubin/.julia/packages/BinaryProvider/UTYxu/src/PlatformEngines.jl:443
│  [4] #download at ./none:0 [inlined]
│  [5] #download_verify#90(::Bool, ::Bool, ::Bool, ::Function, ::String, ::String, ::String) at /home/mlubin/.julia/packages/BinaryProvider/UTYxu/src/PlatformEngines.jl:523
│  [6] #download_verify at ./none:0 [inlined]
│  [7] #install#111(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at /home/mlubin/.julia/packages/BinaryProvider/UTYxu/src/Prefix.jl:353
│  [8] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at ./none:0
│  [9] top-level scope at /home/mlubin/.julia/packages/SpecialFunctions/KvXoO/deps/build.jl:40
│  [10] include at ./boot.jl:317 [inlined]
│  [11] include_relative(::Module, ::String) at ./loading.jl:1038
│  [12] include(::Module, ::String) at ./sysimg.jl:29
│  [13] include(::String) at ./client.jl:388
│  [14] top-level scope at none:0
│ in expression starting at /home/mlubin/.julia/packages/SpecialFunctions/KvXoO/deps/build.jl:2
│ [16:45:59] curl: /home/mlubin/julia-1.0.0/bin/../lib/julia/libcurl.so.4: no version information available (required by curl)
│ [16:45:59] curl: (48) An unknown option was passed in to libcurl
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
```

This is using `BinaryProvider` 0.4.2, and
```
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #117

### CODE REVIEW

**Comment by ararslan** [comment]
Uh, what's with the keyword thing, @staticfloat? That was from the auto-generated build script.

**Comment by ararslan** [comment]
```
┌ Error: Error building `SpecialFunctions`:
│ ERROR: LoadError: MethodError: no method matching Linux(::Symbol; libc=:glibc)
│ Closest candidates are:
│   Linux(::Symbol) at /home/travis/.julia/packages/BinaryProvider/UTYxu/src/PlatformNames.jl:17 got unsupported keyword argument "libc"
│   Linux(::Symbol, !Matched::Symbol) at /home/travis/.julia/packages/BinaryProvider/UTYxu/src/PlatformNames.jl:17 got unsupported keyword argument "libc"
│   Linux(::Symbol, !Matched::Symbol, !Matched::Symbol) at /home/travis/.julia/packages/BinaryProvider/UTYxu/src/PlatformNames.jl:17 got unsupported keyword argument "libc"
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] include at ./boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1038
│  [4] include(::Module, ::String) at ./sysimg.jl:29
│  [5] include(::String) at ./client.jl:398
│  [6] top-level scope at none:0
│ in expression starting at /home/travis/build/JuliaMath/SpecialFunctions.jl/deps/build.jl:16
```
@staticfloat, I copied the stuff from the build.jl file generated in the newest OpenspecfunBuilder tag, and it includes these keyword arguments that are apparently unsupported. Did I do something weird with versions or something?

**Comment by staticfloat** [comment]
I bet you need BP 0.4.2+

**Comment by ararslan** [comment]
It's installing 0.4.2: https://travis-ci.org/JuliaMath/SpecialFunctions.jl/jobs/428456157#L579. Do you mean master?

**Comment by ararslan** [comment]
I removed the keyword argument stuff. Now source builds are failing because I included the `check_deps()` step in `__init__()`, which doesn't exist when deps.jl is generated by BinDeps instead of BinaryProvider...

**Comment by ararslan** [comment]
Fixed and also updated for the combinatorial GCC explosion new world order

**Comment by ararslan** [comment]
64-bit Windows error looks like a similar thing that's been happening with the Julia repo.

**Pull request merged**
